const openButton=document.querySelector('#openGalaxy'),experience=document.querySelector('#experience'),welcome=document.querySelector('#welcome'),song=document.querySelector('#song');let started=false;
openButton.addEventListener('click',()=>{welcome.classList.add('is-opening');experience.classList.add('is-revealing');if(!started){createGalaxy();started=true}song.play().catch(()=>{})});
function createGalaxy(){const canvas=document.querySelector('#galaxy-canvas'),r=new THREE.WebGLRenderer({canvas,antialias:true});r.setPixelRatio(Math.min(devicePixelRatio,2));r.setSize(innerWidth,innerHeight);r.setClearColor(0x020409);const s=new THREE.Scene(),c=new THREE.PerspectiveCamera(52,innerWidth/innerHeight,.1,600);c.position.set(0,19,86);const o=new THREE.OrbitControls(c,r.domElement);o.enableDamping=true;o.enablePan=false;o.minDistance=45;o.maxDistance=118;o.maxPolarAngle=Infinity;o.minPolarAngle=0;o.target.set(0,2,0);s.add(stars());const g=new THREE.Group();g.rotation.x=-.2;s.add(g);g.add(spiral(),sunflower(),centerPhoto());photos(g);words(g);s.add(new THREE.PointLight(0xffd12f,3.2,120),new THREE.AmbientLight(0xffe99a,.5));(function loop(){requestAnimationFrame(loop);g.rotation.y+=.0008;o.update();r.render(s,c)})();addEventListener('resize',()=>{c.aspect=innerWidth/innerHeight;c.updateProjectionMatrix();r.setSize(innerWidth,innerHeight)})}
function stars(){const g=new THREE.BufferGeometry(),n=6800,p=new Float32Array(n*3);for(let i=0;i<n;i++){const a=Math.random()*6.283,r=90+Math.random()*230;p.set([Math.cos(a)*r,(Math.random()-.5)*190,Math.sin(a)*r],i*3)}g.setAttribute('position',new THREE.BufferAttribute(p,3));return new THREE.Points(g,new THREE.PointsMaterial({color:0xffdf4b,size:.62,transparent:true,opacity:.92,blending:THREE.AdditiveBlending}))}
function spiral(){const g=new THREE.BufferGeometry(),n=24500,p=new Float32Array(n*3),co=new Float32Array(n*3),a=new THREE.Color(0xffc816),b=new THREE.Color(0xfffacb);for(let i=0;i<n;i++){const arm=i%4,t=Math.pow(Math.random(),2.4),rad=4+t*75,ang=arm*1.57+rad*.19+(Math.random()-.5)*(.08+t*.42),spread=.45+t*2.4;p.set([Math.cos(ang)*rad,(Math.random()-.5)*spread,Math.sin(ang)*rad],i*3);const x=Math.random()>.45?a:b;co.set([x.r,x.g,x.b],i*3)}g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('color',new THREE.BufferAttribute(co,3));return new THREE.Points(g,new THREE.PointsMaterial({size:.38,vertexColors:true,transparent:true,opacity:.96,blending:THREE.AdditiveBlending,depthWrite:false}))}
function sunflower(){const g=new THREE.BufferGeometry(),n=10500,p=new Float32Array(n*3),co=new Float32Array(n*3),yellow=new THREE.Color(0xffff12),orange=new THREE.Color(0xffaf06),red=new THREE.Color(0x8f2108);for(let i=0;i<n;i++){let x,y,z=-5+(Math.random()-.5)*2,col;if(i<2400){const a=Math.random()*6.283,rr=Math.sqrt(Math.random())*10;x=Math.cos(a)*rr;y=2+Math.sin(a)*rr;col=red}else{const petal=(i%20)/20*6.283,theta=Math.random()*6.283,rad=12+Math.sqrt(Math.random())*15,wide=4.1,deep=8.2;x=Math.cos(petal)*rad+Math.cos(petal)*Math.cos(theta)*deep+Math.cos(petal+1.57)*Math.sin(theta)*wide;y=2+Math.sin(petal)*rad+Math.sin(petal)*Math.cos(theta)*deep+Math.sin(petal+1.57)*Math.sin(theta)*wide;col=Math.random()>.18?yellow:orange}p.set([x,y,z],i*3);co.set([col.r,col.g,col.b],i*3)}g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('color',new THREE.BufferAttribute(co,3));return new THREE.Points(g,new THREE.PointsMaterial({size:.66,vertexColors:true,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false}))}
function circleTexture(path){const image=new Image(),cv=document.createElement('canvas');cv.width=cv.height=512;const x=cv.getContext('2d'),t=new THREE.CanvasTexture(cv);image.src=path;image.onload=()=>{const scale=Math.max(512/image.width,512/image.height),w=image.width*scale,h=image.height*scale;x.clearRect(0,0,512,512);x.beginPath();x.arc(256,256,244,0,6.283);x.clip();x.drawImage(image,(512-w)/2,(512-h)/2,w,h);x.lineWidth=10;x.strokeStyle='#ffe77d';x.beginPath();x.arc(256,256,244,0,6.283);x.stroke();t.needsUpdate=true};return t}
function circle(path,size){const s=new THREE.Sprite(new THREE.SpriteMaterial({map:circleTexture(path),transparent:true,depthWrite:false}));s.scale.set(size,size,1);return s}
function centerPhoto(){const p=circle('assets/foto-central.jpeg',19);p.position.set(0,2,3);const redRing=new THREE.Mesh(new THREE.TorusGeometry(10.25,.62,14,100),new THREE.MeshBasicMaterial({color:0xb73808,transparent:true,opacity:.95}));redRing.position.set(0,2,1.7);const ring=new THREE.Mesh(new THREE.TorusGeometry(12.2,.34,12,100),new THREE.MeshBasicMaterial({color:0xffe035,transparent:true,opacity:1}));ring.position.set(0,2,1.8);const group=new THREE.Group();group.add(p,redRing,ring);return group}
function sprite(text,width=15){const c=document.createElement('canvas');c.width=1200;c.height=180;const x=c.getContext('2d');x.font='700 70px Arial';x.textAlign='center';x.textBaseline='middle';x.shadowColor='#ffc415';x.shadowBlur=28;x.fillStyle='#fff8c5';x.fillText(text,600,90);const s=new THREE.Sprite(new THREE.SpriteMaterial({map:new THREE.CanvasTexture(c),transparent:true,depthWrite:false}));s.scale.set(width,width*.15,1);return s}
function photos(g){const q=['Hermosa','Linda','Bella','Loca','Amable','Empática','Gritona','Preciosa'],f=['flor-1.jpg','flor-2.jpg','flor-3.jpg','flor-4.jpg','flor-5.jpg','flor-6.jpg','flor-7.jpeg','flor-8.jpg'];f.forEach((file,i)=>{const a=i/8*6.283+.22,rad=i%2?52:61,x=Math.cos(a)*rad,y=(i%3-1)*5,z=Math.sin(a)*rad,p=circle(`assets/${file}`,i%3?8:10);p.position.set(x,y,z);g.add(p);const l=sprite(q[i],11);l.position.set(x,y-7,z);g.add(l)})}
function words(g){['Una sonrisa que ilumina','Eres una muy buena personita','Tu luz es unica','Dulce y especial','Siempre unicaaa','Preciosa por dentro y por fuera','Un universo unico','Eres un diamante en bruto'].forEach((t,i)=>{const a=i/8*6.283+.55,rad=76,s=sprite(t,18);s.position.set(Math.cos(a)*rad,(i%4-1.5)*7,Math.sin(a)*rad);g.add(s)})}
